version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - red
    deploy:
      replicas: 2
      placement:
        constraints: [ node.labels.tipo == "python_app" ]

  web:
    build: ./www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:5000/api
    networks:
      - red
    deploy:
      replicas: 2
      placement:
        constraints: [ node.labels.tipo == "node_app" ]

  redis:
    image: redis:latest
    expose:
      - 6379
    networks:
      - red
    deploy:
      replicas: 2
      placement:
        constraints: [ node.labels.tipo == "redis" ]

networks:
  red:
    driver: overlay
